# Generated by Django 4.0.4 on 2022-04-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badcar', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Humi',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
